pipeline:
  name: oracle-to-oracle

source:
  type: oracle
  config:
    host: oracle
    port: 1521
    service_name: FREEPDB1
    user: lab
    password: lab
    query: "SELECT * FROM spacecraft_telemetry_events ORDER BY event_sequence"
    batch_size: 2000

destination:
  type: oracle
  config:
    host: oracle
    port: 1521
    service_name: FREEPDB1
    user: lab
    password: lab
    target_table: events_sink
    mode: atomic
